
# This is a basic workflow to help you get started with Actions

name: Build Wireguard Server

# Controls when the workflow will run
on:
  # Only run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Build Wiregaurd
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh || sudo sh get-docker.sh || echo ${{ secrets.PASSWORD }} | sudo -S sh get-docker.sh
            usermod -aG docker $USER || sudo usermod -aG docker $USER || echo ${{ secrets.PASSWORD }} | sudo -S usermod -aG docker $USER
            mkdir -p wireguard && cd wireguard
            curl -fsSL https://raw.githubusercontent.com/certaintls/build-VPN-server/main/scripts/wg_config_exit_server.sh -o wg_config_exit_server.sh
            curl -fsSL https://raw.githubusercontent.com/certaintls/build-VPN-server/main/scripts/wg_generate_client.sh -o wg_generate_client.sh
            sh wg_config_exit_server.sh
            sh wg_generate_client.sh ${{ secrets.HOST }}
      - name: Configure your client
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd wireguard
            echo 'Please see the client configuration below:'
            echo ' '
            echo '=========================================='
            cat client.conf
            echo '=========================================='
            echo ' '
            echo 'Or scan the QR-code below to configure your client:'
            cat client.conf | docker run --rm -i --net=none thomasleplus/qrcode qrencode -t ANSIUTF8
